### PR TITLE
Adding metadata to applicable state APIs.

### PR DESCRIPTION
**Pull request by artursouza**
# Description

Adding metadata to applicable state APIs.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #114 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [X] Created/updated tests
* [X] Extended the documentation

### CODE REVIEW

**Review by mukundansundar — COMMENTED** [review]
add unit tests?

**Review by youngbupark — APPROVED** [review]

**Comment by youngbupark** [comment]
> add unit tests?

oh that's good point :)

**Comment by artursouza** [comment]
Added unit tests.

**Review by mukundansundar — COMMENTED** [review]
I am able to see that save_state has metadata in the StateItem [definition](https://github.com/dapr/dapr/blob/master/dapr/proto/common/v1/common.proto#L95).
Do we not use it? 
It is documented [here](https://github.com/dapr/docs/blob/master/reference/api/state_api.md#save-state) that metadata can be passed, but we are not passing along the metadata for state item in the save_state call.

**Comment by artursouza** [comment]
> here

Thanks for pointing that out. I did not find the metadata in the request object, so I thought it was not applicable.

**Review by mukundansundar — APPROVED** [review]
Do we need to provide a convenience method to save multiple state? @youngbupark

**Comment by artursouza** [comment]
> Do we need to provide a convenience method to save multiple state? @youngbupark

This is another scope. I noticed this too. I will merge this PR in the meantime.

**Comment by youngbupark** [comment]
> > Do we need to provide a convenience method to save multiple state? @youngbupark
> 
> This is another scope. I noticed this too. I will merge this PR in the meantime.

That's the another issue. but the other sdk supports multiple states save ?

**Pull request merged**
