### PR TITLE
Complete validation tests for Metadata gRPC API.

### LINKED ISSUE #445: Update Metadata API example code to check for all fields in response object.
## Expected Behavior

The current GRPC implementation of the [Metadata API] in dapr 1.18 returns a response missing some fields. 

Tracking issues in dapr/dapr:
1. dapr/dapr#5051, 
2. dapr/dapr#5038 and 
3. dapr/dapr#5018.

In the current stable version of Dapr, only `extended_metadata` is returned correctly. This should be addressed in dapr/dapr itself but, once it is, we need to update our example for the Metadata API to check for these missing fields.

File `examples/metadata/app.py` should be updated to something like
```diff
--- a/examples/metadata/app.py
+++ b/examples/metadata/app.py
@@ -28,12 +28,10 @@ def main():

         print("Now, we will fetch the sidecar's metadata ")
         metadata = dapr.get_metadata()
+        print(f'{metadata.application_id=}"')
+        print(f'{metadata.active_actors_count=} should be non-empty')
+        print(f'{metadata.registered_components=} should be non-empty')
+        print(f'{metadata.extended_metadata=} should be non-empty')

         old_value = metadata.extended_metadata[extended_attribute_name]
```

and `examples/metadata/README.md` should be updated to something like

```diff
--- a/examples/metadata/README.md
+++ b/examples/metadata/README.md
@@ -34,6 +34,10 @@ name: Run state store example
 expected_stdout_lines:
   - "== APP == First, we will assign a new custom label to Dapr sidecar's"
   - "== APP == Now, we will fetch the sidecar's metadata"
+  - "== APP == metadata.application_id='' but should be "my-metadata-app""
+  - "== APP == metadata.active_actors_count={} but should be non-empty"
+  - "== APP == metadata.registered_components=[] but should be non-empty"
+  - "== APP == metadata.extended_metadata={'is-this-our-metadata-example': 'yes'}"
   - "== APP == We will update our custom label value and check it was persisted"
   - "== APP == We added a custom label named extended_attribute_name='is-this-our-metadata-example'"
   - "== APP == Its old value was old_value='yes' but now it is new_value='You bet it is!'"
@@ -50,6 +54,10 @@ The output should be as follows:
 == APP == First, we will assign a new custom label to Dapr sidecar's
 == APP == Now, we will fetch the sidecar's metadata
+== APP == metadata.application_id='' but should be "my-metadata-app"
+== APP == metadata.active_actors_count={} but should be non-empty
+== APP == metadata.registered_components=[] but should be non-empty
+== APP == metadata.extended_metadata={'is-this-our-metadata-example': 'yes'}
 == APP == We will update our custom label value and check it was persisted
 == APP == We added a custom label named extended_attribute_name='is-this-our-metadata-example'
 == APP == Its old value was old_value='yes' but now it is new_value='You bet it is!'
```

## Actual Behavior

As of now, the only field that that is set on GetMetadata from the GRPC Metadata API api is `extended_metadata`.

## Steps to Reproduce the Problem

Updating `examples/metadata/app.py` from PR #446 with the diff above and invoking `app.py` as documented in the companion README  should be enough to verify this. Obviously, there might be a bug in the Python SDK, in the way we convert the GRPC object into a more python-friendly code. To avoid circumvent this, one can directly print returned `GetMetadataResponse` protocol buffer as returned by the GRPC API itself. 

## Release Note

RELEASE NOTE: **FIX** Updated Metadata API examples to account for fixes in Dapr GRPC endpoint implementation.

[Metadata API]: https://docs.dapr.io/reference/api/metadata_api/

### PR DESCRIPTION
**Pull request by tmacam**
# Description

This PR completes the work started on #446 and fixes #445 and completes
the work for #410.

It depends the fix for dapr/dapr#5051 to be included in the stable release.

## Issue reference

Please reference the issue this PR will close: #445 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation

### CODE REVIEW

**Comment by tmacam** [comment]
For the record: validation tests will fail until fixes for all dapr/dapr#5051 make to the stable release.

**Comment by berndverst** [comment]
@tmacam could you please complete this PR? You can use `/ok-to-test` to kick off the workflow that runs the `validate-examples` against the latest dapr/dapr build from master branch (go to the actions tab to see the test run). This way you can ensure everything works. Let me know when you got the examples working (you can ignore any failure in the configuration API test -- there is some flakiness in response ordering).

**Comment by berndverst** [comment]
Test run against latest dapr/dapr master as of this time: https://github.com/dapr/python-sdk/actions/runs/3154300744

**Comment by tmacam** [comment]
All tests are failing on example on `./validate.sh configuration`

**Comment by berndverst** [comment]
As I said don't worry about that. Then update your PR and move your test before the configuration one please @tmacam

**Review by berndverst — APPROVED** [review]

**Pull request merged**
