### PR TITLE
Change configuration API response to dictionary

### PR DESCRIPTION
**Pull request by hunter007**
# Description

When https://github.com/dapr/dapr/pull/4695 merged, I will test the PR, then it should be reviewed by someone.

the PR can be merged after that https://github.com/dapr/dapr/pull/4695 is merged.

## Issue reference

Please reference the issue this PR will close: #411

### CODE REVIEW

**Comment by berndverst** [comment]
Thanks for this PR. We will still need to wait for the dapr/dapr PR to be completed and at that time we will need to update the protos before we can merge this.

**Comment by hunter007** [comment]
> 
That's OK， I will update codes.

**Comment by berndverst** [comment]
I manually verified this change in its current form against a custom build of `dapr/dapr`

**Review by berndverst — APPROVED** [review]

**Review by berndverst — APPROVED** [review]

**Review by berndverst — DISMISSED** [review]

**Review by mukundansundar — APPROVED** [review]

**Comment by berndverst** [comment]
@hunter007 please do not update this PR anymore. I will manage this PR from here.

**Review by berndverst — APPROVED** [review]

**Review by berndverst — APPROVED** [review]

**Comment by hunter007** [comment]
> @hunter007 please do not update this PR anymore. I will manage this PR from here.

okay

**Pull request merged**
