### PR TITLE
Brings back a docs link that was removed because it wasn’t online yet

### PR DESCRIPTION
**Pull request by elena-kolevska**
Brings back the link we removed because it wasn’t online yet

### CODE REVIEW

**Comment by elena-kolevska** [comment]
@berndverst this link wasn't online until today and we changed it so the examples tests wouldn't fail. 
The documents just got published, so I'm adding back the link.

**Comment by berndverst** [comment]
@elena-kolevska linter ruff autoformatter is failing. Can you update?

**Comment by elena-kolevska** [comment]
Since version 0.3.0 the ruff autoformatter conflicts with flake8. I think this is something we have to decide and send a  separate PR for.

**Comment by berndverst** [comment]
I pinned 0.2.2 now and updated your PR

**Pull request merged**
