### PR TITLE
only serialize failure details if they exist

### PR DESCRIPTION
**Pull request by akshaya-a**
# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #691

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by elena-kolevska** [comment]
Hey @akshaya-a , thanks for your PR. Could you please sign your commit? Here's how to do it:


Rebase the branch

If you have a local git environment and meet the criteria below, one option is to rebase the branch and add your Signed-off-by lines in the new commits. Please note that if others have already begun work based upon the commits in this branch, this solution will rewrite history and may cause serious issues for collaborators ([described in the git documentation](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) under "The Perils of Rebasing").

You should only do this if:

    You are the only author of the commits in this branch
    You are absolutely certain nobody else is doing any work based upon this branch
    There are no empty commits in the branch (for example, a DCO Remediation Commit which was added using --allow-empty)

To add your Signed-off-by line to every commit in this branch:

    Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
    In your local branch, run: git rebase HEAD~1 --signoff
    Force push your changes to overwrite the branch: git push --force-with-lease origin ak/guard-workflow-state-failure-details

**Comment by elena-kolevska** [comment]
I was able to reproduce this locally and test the fix. Looks good. I would love an added test for it, though.

**Comment by berndverst** [comment]
@akshaya-a please do the following or this cannot be merged.

To add your Signed-off-by line to every commit in this branch:

Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: git rebase HEAD~1 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin ak/guard-workflow-state-failure-details

**Comment by akshaya-a** [comment]
@elena-kolevska  @berndverst  sorry for the delay, was focused on some stuff for //build

yeah the only reason I didn't bother signing yet was I assumed we'd want a test covering the failure but in my project I worked around it by just reaching in to the .__obj for debugging purposes, reducing the immediate priority

i can probably get to this next week?

**Comment by akshaya-a** [comment]
ah didn't realize i already had a codespace for this repo, no need to be lazy - signed in case you want to merge, but happy to add a test later

**Review by berndverst — APPROVED** [review]

**Comment by marcduiker** [comment]
@holopin-bot @akshaya-a Thank you!

**Pull request merged**
