### PR TITLE
Fix: RecursionError in conf settings class when accessing unimplemented settings 

### PR DESCRIPTION
**Pull request by ryou90**
# Description

~Remove __getattr__ method from settings class.~

Maintainer Edit: Raise `AttributeError` for properties not supported by the `Settings` class.

## Issue reference

Please reference the issue this PR will close: #539 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by berndverst** [comment]
This PR breaks our type checking. You can verify yourself, in general I recommend running the following in order:

```
pip3 install -r dev-requirements.txt
tox -e py39 # or tox -e py311 etc, depends on your Python version
tox -e flake8
tox -e type
tox -e examples
```

Please note that `settings.py` is also imported by at least one of the following packages `dapr-ext-grpc`, `dapr-ext-fastapi`, and `flask-dapr`. Those are in the `ext` folder of this repo.

The method you are removing may be required for those packages to work correctly as this code is shared.

**Review by berndverst — CHANGES_REQUESTED** [review]
This breaks type checks. I left instructions for you to run all relevant tests locally. I'll revisit the PR once all tests I pointed out pass.

The recursion issue you mentioned only occurs when accessing something which doesn't exist right? Our settings class is intended to be used for Dapr constants. So a recursion issue that exists when accessing a variable which isn't defined by Dapr seems like a very minor inconvenience. Not something I'd include in a hotfix for example.

**Comment by berndverst** [comment]
```
dapr/clients/grpc/client.py:119: error: "Settings" has no attribute "DAPR_RUNTIME_HOST"  [attr-defined]
dapr/clients/grpc/client.py:119: error: "Settings" has no attribute "DAPR_GRPC_PORT"  [attr-defined]
dapr/clients/grpc/client.py:132: error: "Settings" has no attribute "DAPR_API_TOKEN"  [attr-defined]
dapr/clients/grpc/client.py:134: error: "Settings" has no attribute "DAPR_API_TOKEN"  [attr-defined]
ext/dapr-ext-grpc/dapr/ext/grpc/app.py:68: error: "Settings" has no attribute "GRPC_APP_PORT"  [attr-defined]
dapr/clients/http/client.py:53: error: "Settings" has no attribute "DAPR_RUNTIME_HOST"  [attr-defined]
dapr/clients/http/client.py:54: error: "Settings" has no attribute "DAPR_HTTP_PORT"  [attr-defined]
dapr/clients/http/client.py:55: error: "Settings" has no attribute "DAPR_API_VERSION"  [attr-defined]
dapr/clients/http/client.py:68: error: "Settings" has no attribute "DAPR_API_TOKEN"  [attr-defined]
dapr/clients/http/client.py:69: error: "Settings" has no attribute "DAPR_API_TOKEN"  [attr-defined]
dapr/clients/__init__.py:75: error: "Settings" has no attribute "DAPR_API_METHOD_INVOCATION_PROTOCOL"  [attr-defined]
Installing missing stub packages:
/home/runner/work/python-sdk/python-sdk/.tox/type/bin/python -m pip install types-colorama types-python-dateutil types-ujson


Found 15 errors in 7 files (checked 59 source files)
dapr/clients/__init__.py:79: error: "Settings" has no attribute "DAPR_HTTP_TIMEOUT_SECONDS"  [attr-defined]
dapr/actor/runtime/runtime.py:48: error: "Settings" has no attribute "DAPR_HTTP_TIMEOUT_SECONDS"  [attr-defined]
dapr/actor/client/proxy.py:49: error: "Settings" has no attribute "DAPR_HTTP_TIMEOUT_SECONDS"  [attr-defined]
examples/demo_actor/demo_actor/demo_actor_flask.py:46: error: "Settings" has no attribute "HTTP_APP_PORT"  [attr-defined]
type: exit 1 (25.17 seconds) /home/runner/work/python-sdk/python-sdk> mypy --config-file mypy.ini pid=2304
  type: FAIL code 1 (48.97=setup[16.32]+cmd[2.09,2.08,3.32,25.17] seconds)
  evaluation failed :( (49.04 seconds)
  ```

**Comment by tmacam** [comment]
I think adding a unit test would also be quite valuable for this PR. Yes, it is a simple change but it would help document this PR and avoid a regression.

**Review by ourway — APPROVED** [review]

**Comment by berndverst** [comment]
@ourway why do you approve this? Please look at the comments I left here which need to be addressed.

**Review by ourway — CHANGES_REQUESTED** [review]
Sorry, I hit the wrong option by mistake before.

**Review by berndverst — APPROVED** [review]

**Review by berndverst — APPROVED** [review]

**Pull request merged**
