### PR TITLE
fix timer context

### PR DESCRIPTION
**Pull request by psychomelet**
Currently timer callback using the reminder context, this PR fixed it.

### CODE REVIEW

**Comment by wcs1only** [comment]
This commit is missing a signoff signature. Can you please add one?:

```
git commit --amend --no-edit --signoff
git push --force <your_remote> <your_branch>
```

**Review by berndverst — APPROVED** [review]
Thanks for catching this!

**Review by paulyuk — COMMENTED** [review]
Change looks good.  Thank you for the contribution.

**Comment by berndverst** [comment]
@psychomelet can you please sign your commits per our requirement?

```
git commit --amend --no-edit --signoff
git push --force <your_remote> <your_branch>
```

**Review by berndverst — APPROVED** [review]

**Pull request merged**
