### PR TITLE
Python SDKDocs updates for v1.2 client

### PR DESCRIPTION
**Pull request by paulyuk**
# Description

Updated Python SDK docs for the client:
- changed all example links to point to the main branch, versus old setup branch 1+ years old
- updated all sample code to reflect current 1.2 SDK for Python
- added complementary Subscribe example to Publish & subscribe to messages section

## Issue reference

Fixes #1551 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [] Created/updated tests
* [x] Extended the documentation

### CODE REVIEW

**Comment by paulyuk** [comment]
@wcs1only @berndverst  could you please help review how I branched here?  The docs were sparse on branching technique for a submodule like PythonSDK.  I did work in my own branch and pushed to that branch, since obviously I cannot and should not to the main.  Please advise.  I wonder if that's why the build check broke too?

**Comment by berndverst** [comment]
LGTM

**Comment by wcs1only** [comment]
> @wcs1only @berndverst could you please help review how I branched here? The docs were sparse on branching technique for a submodule like PythonSDK. I did work in my own branch and pushed to that branch, since obviously I cannot and should not to the main. Please advise. I wonder if that's why the build check broke too?

@paulyuk You did things right, the build failure looks unrelated, as another PR is failing in the same place. I suspect there may have been a change in one of our dependencies that might be tripping things up. Will take a look today.

**Comment by berndverst** [comment]
> > @wcs1only @berndverst could you please help review how I branched here? The docs were sparse on branching technique for a submodule like PythonSDK. I did work in my own branch and pushed to that branch, since obviously I cannot and should not to the main. Please advise. I wonder if that's why the build check broke too?
> 
> @paulyuk You did things right, the build failure looks unrelated, as another PR is failing in the same place. I suspect there may have been a change in one of our dependencies that might be tripping things up. Will take a look today.

Looks related to protobuff library stubs missing for type checking. Either `mypy --install-types` or adding the `types-protobuf` requirement should resolve it. Agree this should be done in another PR. @wcs1only

**Review by wcs1only — APPROVED** [review]
Nice work! Thanks for cleaning this up!

**Comment by paulyuk** [comment]
Thank you @wcs1only  and @berndverst !

**Pull request merged**
